export const ROUTES = {
  login: '/login',
  onboarding: '/onboarding',
  dashboard: '/',
  pos: '/pos',
  receipt: (saleId = ':saleId') => `/pos/comprobante/${saleId}`,
  cash: '/caja',
  closeCash: '/caja/cerrar',
  cashHistory: '/caja/historial',
  cashDetail: (id = ':id') => `/caja/${id}`,
  cashClosure: (id = ':id') => `/caja/${id}/cierre`,
  products: '/productos',
  productCreate: '/productos/nuevo',
  productDetail: (id = ':id') => `/productos/${id}`,
  productEdit: (id = ':id') => `/productos/${id}/editar`,
  categories: '/categorias',
  brands: '/marcas',
  combos: '/combos',
  inventory: '/inventario',
  inventoryMovements: '/inventario/movimientos',
  customers: '/clientes',
  customerDetail: (id = ':id') => `/clientes/${id}`,
  sales: '/ventas',
  saleDetail: (id = ':id') => `/ventas/${id}`,
  returns: '/devoluciones',
  returnCreate: '/devoluciones/nueva',
  suppliers: '/proveedores',
  supplierDetail: (id = ':id') => `/proveedores/${id}`,
  purchases: '/compras',
  purchaseCreate: '/compras/nueva',
  purchaseDetail: (id = ':id') => `/compras/${id}`,
  promotions: '/promociones',
  expenses: '/gastos',
  reports: '/reportes',
  exports: '/exportaciones',
  users: '/usuarios',
  audit: '/auditoria',
  notifications: '/notificaciones',
  tools: '/herramientas',
  settings: '/configuracion',
  noPermission: '/sin-permiso',
} as const;
